### ISSUE TITLE
[`usd-cpp`] `build_usd.py` does not find something

### ISSUE THREAD

**Issue by virtualritz** [luke-titley/usd-rs#21]
What I did:

```
git clone https://github.com/luke-titley/usd-rs.git
cd usd-rs
git submodule update --init --recursive
cargo build
```

Specifically the command in [line 28ff in `usd-cpp/build.rs`](https://github.com/luke-titley/usd-rs/blob/5b7bb0ba3edec2a6178faf41656da344711084f5/usd-cpp/build.rs#L28-L52) fails:

```
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', usd-cpp/build.rs:54:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

~~It seems `cpp_out_dir` does not exist when the resp. Python script is ran:~~
```
ls /home/moritz/code/crates/usd-rs/target/debug/build/usd-cpp-d36b3ba0259f6455/out/install
"/home/moritz/code/crates/usd-rs/target/debug/build/usd-cpp-d36b3ba0259f6455/out/install": No such file or directory (os error 2)
```

**Comment by virtualritz** [comment]
I take that back.

I created the folder manually but I get the same error. I.e. it seems this is bubbled up from Python: the `build_usd.py` does not find something.

Any idea what that could be?

**Comment by kubo-von** [comment]
Hi @virtualritz,
I think this might be the same error I encountered, it was python 2 vs python 3 mixup. Solved by:
`sudo apt install python-is-python3`

**Comment by virtualritz** [comment]
> I think this might be the same error I encountered, it was python 2 vs python 3 mixup.

That was it. I suggest adding a python version check to `build.rs` or maybe even upstream, at the USD repo?

I can look into the former this week and open a PR if people think it makes sense.

**Comment by luke-titley** [comment]
Ive been off radar for a while. Do t know why I didn't get notification if this. Yes please if you make the MR I'll merge it.
